# _config.yml for Minimal Mistakes theme

title: "Anthony Canzona — Data Portfolio"
description: "FP&A, Financial Modeling, and Data Analytics for Tech & E-commerce"
url: "https://notanth.github.io"
baseurl: "" # Leave blank for user.github.io site

# Theme settings
remote_theme: "mmistakes/minimal-mistakes@4.24.0"

# Author information
author:
  name: "Anthony Canzona"
  avatar: "/assets/images/profile.jpg" # Remove or update if no profile image
  bio: "Financial Analyst | Data Analytics | Python | SQL | Tableau"
  location: "Austin, TX"
  links:
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/in/anthonyscanzona/"
    - label: "📰 Substack: Anth’s Newsletter"
      icon: "fas fa-newspaper"
      url: "https://anth.substack.com/"
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/notanth"

# Navigation bar
navigation:
  - title: "Home"
    url: /
  - title: "Portfolio"
    url: /portfolio/
  - title: "Let's Connect"
    url: /#lets-connect

# Plugins (GitHub Pages safe list)
plugins:
  - jekyll-remote-theme
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag

# Markdown & syntax highlighting
markdown: kramdown
highlighter: rouge

# Minimal Mistakes theme options
minimal_mistakes_skin: "air" # Options: air, dark, mint, neon, etc.
search: true
logo: "" # Optional: add path to logo image if you have one

# Exclude from build
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
