# _config.yml for Minimal Mistakes theme

title: "Anthony Canzona — Data Portfolio"
description: "FP&A, Financial Modeling, and Data Analytics for Tech & E-commerce"
url: "https://notanth.github.io"
baseurl: "" # Leave blank for user.github.io site

# Theme settings
remote_theme: "mmistakes/minimal-mistakes@4.24.0"

# Author information
author:
  name: "Anthony Canzona"
  avatar: "/assets/images/profile.jpg" # Remove or update if no profile image
  bio: "Financial Analyst | Data Analytics | Python | SQL | Tableau"
  location: "Austin, TX"
  links:
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/in/anthonycanzona/"
    - label: "📰 Substack: Anth’s Newsletter"
      icon: "fas fa-newspaper"
      url: "https://anth.substack.com/"
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/notanth"

# Site navigation
collections:
  projects:
    output: true
    permalink: /projects/:path/

defaults:
  - scope:
      path: ""
      type: projects
    values:
      layout: single
      author_profile: true

# Navigation bar
navigation:
  - title: "Home"
    url: /
  - title: "Experience"
    url: /about/
  - title: "Projects"
    url: /projects/
  - title: "Let's Connect"
    url: /connect/

# Plugins (GitHub Pages safe list)
plugins:
  - jekyll-remote-theme
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag

# Pagination (for blog if you add posts)
paginate: 5
paginate_path: /page:num/

# Markdown & syntax highlighting
markdown: kramdown
highlighter: rouge

# Exclude from build
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

# Minimal Mistakes theme options
minimal_mistakes_skin: "air" # Options: air, dark, mint, neon, etc.
search: true
logo: "/assets/images/logo.png" # Optional - remove if no logo
